### ISSUE TITLE
Alternate ports and TLS options?

### ISSUE THREAD

**Issue by asdfhjk1** [madprops/airc#1]
I want to try this connecting to localhost:9999 with no tls

Any idea how we can do this?

**Comment by asdfhjk1** [comment]
It seems 6667 is hardcoded

`/node_modules/matrix-org-irc/lib/irc.js` line 96

**Comment by madprops** [comment]
Did you try `server` to that in the config?

It uses: https://github.com/matrix-org/node-irc

I would check if node-irc accepts that syntax.

But when I try connecting with server as `localhost:9999` it tries to connect without throwing an error, so maybe it works.

Edit: I see, I guess you'd need to deal with it at node-irc level.

**Comment by asdfhjk1** [comment]
Indeed, tried that. It hangs on "Joining" like this:

🟢 Starting: chatgpt
🟢 Started anti-spam
🟢 Started openai
🟢 Joining irc...

Now when you edit the lib I just mentioned changing it to 9999 it will connect immediately:

🟢 Starting: chatgpt
🟢 Started anti-spam
🟢 Started openai
🟢 Joining irc...
🟢 Joined #main

**Comment by asdfhjk1** [comment]
By the way, I'm hitting a 429 rate limit on my first question..

Do you think maybe I need a paid plan to actually try this?

Thanks

**Comment by madprops** [comment]
I have only tried it with a paid API key.

**Comment by asdfhjk1** [comment]
Good to know, thank you!

We can close this out I think, feel free. It's maybe a problem upstream I guess if anyone cares.

**Comment by madprops** [comment]
It seems there's a port opt on node-irc, I'm going to see if it's configurable

**Comment by madprops** [comment]
Maybe it works now. If you set the port to something else.

https://github.com/madprops/airc/blob/main/config.json#L6

Edit: Also the rate limit error might be if you used davinci as the model, since davinci is now deprecated.

**Comment by asdfhjk1** [comment]
Indeed, that was it regarding the port. Nice.

**Comment by asdfhjk1** [comment]
I put my card on my account and then I was able to get it working. Honestly I threw $5 bucks at it, too, so that might have been it also, not sure.

**Comment by asdfhjk1** [comment]
Cool project, thanks for making it.

**Comment by madprops** [comment]
@asdfhjk1 Glad it works. The api is relatively cheap, $5 should last you a whole month or so with moderate usage.

**Comment by asdfhjk1** [comment]
Last question,

When it replies to me, I see a crab character where there could be a multi-lined IRC message, it makes it difficult to read, for example

chatgpt: write a bash for loop example
👾 for i in 1 2 3 4 5; do 👾 echo "Number: $i" 👾 done 👾 # This for loop will loop through the numbers 1, 2, 3, 4, and 5. 👾 # It will print out each number preceded by the word "Number". 👾 # The output will be: 👾 # Number: 1 👾 # Number: 2 👾 # Number: 3 👾 # Number: 4 👾 # Number: 5

Do you know how to make it just blow up the irc conversation with multiple messages instead of these emojis?

**Comment by madprops** [comment]
@asdfhjk1 The crab character is your bot's `avatar` this can be changed. But the behavior on multiple lines is controlled by the `compact` setting. Tell your bot this: `botname, !compact false` and it will set compact to false and save it on its config file.

**Comment by asdfhjk1** [comment]
oh, thanks. Yeah I hacked it by making the avatar '\n', your way seems better.
